services:
    db:
        image: mongo:8.0.1
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
        volumes:
            - /data/db
        ports:
            - "27017:27017"

    db-client:
        image: mongo-express:1.0.2-20-alpine3.19
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://admin:${DB_PASS}@db:27017/mea?authSource=admin
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: ${DB_CLIENT_PASS}
        depends_on:
            - db
        ports:
            - "8081:8081"
